### ISSUE TITLE
Feature extraction matching issue

### ISSUE THREAD

**Issue by romanlutz** [romanlutz/NFLPlayPrediction#2]
When using extract_features(2013, 2014) I ran into the following error: (it won't happen for 2014, 2014!)

"NFLPlayPrediction/features.py", line 118, in extract_features
    match = rematch.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

I'm not really sure why it happens, but I'll look into it. Please do the same if you can!

**Comment by valentin012** [comment]
Working on it :)

Am 11.11.2015 um 16:37 schrieb Roman Lutz:

**Comment by valentin012** [comment]
Problem fixed.

**Comment by romanlutz** [comment]
"features.py", line 156, in extract_features
    match = rematch.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

Still happens for me. You can execute the main method of mine with 2013 and 2014, it will yield that error. Actually, it also happens for just 2014,2014 now.

**Comment by valentin012** [comment]
Now it's fixed.

Am 11.11.2015 um 20:50 schrieb Roman Lutz:

**Comment by romanlutz** [comment]
Put in 2009, 2014 and it'll fail again. I think there are some strange plays we don't filter for yet.

If you don't mind I think it's best if you fix it since you wrote it and I took quite some time to understand what's going on there. In the meanwhile I can take the 2014,2014 data and try to use Neural Nets. Ok?

**Comment by valentin012** [comment]
You are right. I have only tested 2013 and 2014. Will fix the other 
years tomorrow morning.
Using Neural Nets sounds good.

Am 11.11.2015 um 21:29 schrieb Roman Lutz:

**Comment by romanlutz** [comment]
No hurries! Thanks for looking into it!
